---
- name: create an ubuntu container on all servers and mount a volume
  hosts: all
  tasks:
    - name: create ubuntu container
      docker_container:
        name: myubuntu
        image: ubuntu
        tty: yes
        interactive: yes
        volumes:
          - /data
...            
