---
- name: Configure apache using child playbooks
  hosts: all
  tasks:
    - name: Install multiple playbook
      include_tasks: "{{item}}"
      with_items:
        - install.yml
        - edit.yml
        - restart.yml
        - check_url.yml
...        
