---
- name: Install nginx
  hosts: all
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Copy the file
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
    - name: restart the nginx
      service:
        name: nginx
        state: restarted
    - name: check if nginx is available
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.47.36
        - http://172.31.35.161
...          
