---
- name: Install git in ubuntu server
  hosts: ubuntu
  tasks:
    - name: install git using apt module
      apt:
        name: git
        state: present
        update_cache: yes
- name: install git in redhat server
  hosts: redhat
  tasks:
    - name: install git using yum module
      yum:
        name: git
        state: present
        update_cache: yes
...          
