---
- name: fetch the file
  hosts: 172.31.47.36
  tasks:
    - name: fetch
      fetch:
        src: file1
        dest: /tmp
- name: copy the file
  hosts: 172.31.35.161
  tasks:
    - name: fetch the file
      copy:
        src: /tmp/172.31.47.36/file1
        dest: /home/ubuntu
...          
