---
- name: Implementing playscope varaiables
  hosts: all
  vars:
    - a: maven
    - b: present
    - c: yes
  tasks:
    - name: install s/w's
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...          

