---
- name: create folder and copy the data
  hosts: all
  tasks:
    - name: create a folder
      file:
        name: /tmp/file1
        state: directory
    - name: copythe file
      copy:
        src: /etc/passwd
        dest: /tmp/file1     
...
