---
- name: Installdockeron allservers
  hosts: all
  tasks:
    - name: install docker
      shell: "{{item}}"
      with_items:
        - curl -fsSL https://get.docker.com -o install-docker.sh
        - sudo sh install-docker.sh
...          
