---
- name: Install git on allservers
  hosts: all
  tasks:
    - name: install git on ubuntu server
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution=="Ubuntu"
...        
