---
- name: create a user and create files/dir in home location
  hosts: all
  tasks:
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: Create a file
      file:
        name: "{{d}}"
        state: "{{e}}"
...          
