---
- name: Delete if the file is executable
  hosts: all
  tasks:
    - name: get info about the file
      stat:
        path: /tmp/file1
      register: result
    - name: Display the result
      debug:
         var: result
    - name: delete if file is executable
      file: 
        name: /tmp/file1
        state: absent
      when: result.stat.executable == true
...        
