---
- name: Create a folder and download jenkins file
  hosts: all
  tasks:
    - name: create a folder
      file:
        name: /tmp/jenkins
        state: directory
    - name: download jenkins file
      get_url:
        url: https://get.jenkins.io/war-stable/2.462.3/jenkins.war
        dest: /tmp/jenkins
    - name: change permission forjenkins war file
      file:
        name: /tmp/jenkins/jenkins.war
        mode: 700
...          
