---
- name: configure tomcat using loop 
  hosts: all
  tasks:
    - name: install tomcat10 and tomcat10-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: yes}
        - {a: tomcat10-admin,b: present,c: no}
    - name: copy the tomcat-users file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: replace port
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: restart the service
      service:
        name: tomcat10
        state: restarted
    - name: pause
      pause:
        seconds: 30      
    - name: check url's
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.47.36:9090
        - http://172.31.35.161:9090
...          
